[package]
name = "selectors_ast"
version = "0.1.0"
authors = ["Ivan Nikulin <inikulin@cloudflare.com>"]
edition = "2018"

[dependencies]
lol_html = { path = "../../", features=["integration_test"] }
serde_json = "1.0.5"
