[package]
name = "selectors_ast"
authors = ["Ivan Nikulin <inikulin@cloudflare.com>"]
edition = "2024"

publish = false

[dependencies]
lol_html = { path = "../../", features=["integration_test"] }
serde_json = "1.0.140"
