[package]
name = "parser_trace"
version = "0.1.0"
authors = ["Ivan Nikulin <inikulin@cloudflare.com>"]
edition = "2021"

publish = false

[dependencies]
encoding_rs = "0.8.13"
lol_html = { path = "../../", features=["integration_test", "debug_trace"] }
getopts = "0.2.15"
